### ISSUE TITLE
Long initialization and data loading time due to too much requests in cache

### ISSUE THREAD

**Issue by frievb** [fluves/pywaterinfo#52] opened 2022-03-31 09:50 UTC
* pywaterinfo version: 0.6.0
* Python version: 3.9.7
* Operating System: Windows 10

### Description

I was using pywaterinfo intensely to load a lot of data and was reloading this data multiple times a day to keep track of the last incoming measurements of some measurement stations.
Suddenly the initialization time went up from less than a second to 30 - 60 minutes. Likewise, data loading times went up extremely . 

### Solution
The big amount of data requests probably caused such an increase of data stored in the pywaterinfo cache memory that it slowed down processing speeds. This was easily solved by clearing the cache:

```
from pywaterinfo import Waterinfo
vmm = Waterinfo("vmm")
vmm.clear_cache()
```

**Comment by stijnvanhoey** [comment] 2022-04-01 12:08
@frievb thanks a lot for reporting the issue and documenting the solution. I added an additional warning to the caching section of the documentation to document this to other users as well, see https://github.com/fluves/pywaterinfo/pull/53

**Comment by stijnvanhoey** [comment] 2023-03-31 13:05
Thanks for reporting. We can certainly improve the caching logic, so let's try to understand what is happening with the cache and provide a better implementation. A first option could be that with the [current fixed-period](https://github.com/fluves/pywaterinfo/blob/master/src/pywaterinfo/waterinfo.py#L32) the cache becomes too large to be manageable. Could you please check:

- What is the size of the file 'C:\Users\VBAUWELF\AppData\Local\Temp\pywaterinfo_cache.sqlite'?
- If you remove the file manually and retry the code, is the issue still there?

**Comment by frievb** [comment] 2023-03-31 13:25
- The size of the sqlite file was 272 KB.
- Once that file is removed, the issue seems to be solved. However, after a couple of small calls, the code hangs again on the same  step (this time when the sqlite file was 184 KB).

**Comment by stijnvanhoey** [comment] 2023-03-31 15:46
> Once that file is removed, the issue seems to be solved

As the size is not the issue but the file existence itself, maybe some interference with other processes?

- Could it be that there is another process or program syncing this file? For example one-drive or something like that? 
- Just to check, there is no other pywaterinfo-based script running or anything multiprocessing used? 

Furthermore, could you provide the versions you use for the packages? When using pip/virtualenv you can use `!pip list` or   with conda `!conda list`. Of main interest is pywaterinfo itself and `requests`, `requests-cache`.

**Comment by frievb** [comment] 2023-04-03 08:03
- As far as I can see, the file is not being synced (not in One-Drive or anything similar). 
- There are no multiple pywaterinfo-based scripts running at the same time. If two scripts are using pywaterinfo at the same time, a clear error is shown: 'database locked'.


The versions of the packages:
```
Name                    Version        
...       
pywaterinfo               0.6.0          
pyyaml                    6.0            
qt                        5.12.9         
rasterio                  1.2.10         
requests                  2.28.1         
requests-cache            1.0.0          
...
```
The output of a successful run looks slightly different than a failed run, but looks still slightly different than your output:
```
2023-04-03 08:50:04,268 requests_cache.backends __init__.py DEBUG: Initializing backend: sqlite pywaterinfo_cache.sqlite
2023-04-03 08:50:04,269 requests_cache.backends.base base.py DEBUG: Initialized SQLiteDict with serializer: SerializerPipeline(name=pickle, n_stages=2)
2023-04-03 08:50:04,273 requests_cache.backends.sqlite sqlite.py DEBUG: Opening connection to C:\Users\USER\AppData\Local\Temp\pywaterinfo_cache.sqlite:responses
2023-04-03 08:50:04,318 requests_cache.backends.base base.py DEBUG: Initialized SQLiteDict with serializer: None
2023-04-03 08:50:04,322 requests_cache.backends.sqlite sqlite.py DEBUG: Opening connection to C:\Users\USER\AppData\Local\Temp\pywaterinfo_cache.sqlite:redirects
2023-04-03 08:50:04,364 urllib3.connectionpool connectionpool.py DEBUG: Starting new HTTP connection (1): download.waterinfo.be:80
2023-04-03 08:50:04,439 urllib3.connectionpool connectionpool.py DEBUG: http://download.waterinfo.be:80 "POST /kiwis-auth/token HTTP/1.1" 201 549
2023-04-03 08:50:04,445 root waterinfo.py INFO: Current token expires on 2023-04-04 08:50:04.445426
2023-04-03 08:50:04,454 requests_cache.policy.actions actions.py DEBUG: Cache directives from request headers: CacheDirectives()
2023-04-03 08:50:04,454 requests_cache.policy.actions actions.py DEBUG: Pre-read cache checks: Passed
2023-04-03 08:50:04,456 requests_cache.policy.actions actions.py DEBUG: Post-read cache actions: CacheActions(expire_after=datetime.timedelta(days=7), send_request=True)
2023-04-03 08:50:04,463 urllib3.connectionpool connectionpool.py DEBUG: Starting new HTTPS connection (1): download.waterinfo.be:443
2023-04-03 08:50:04,644 urllib3.connectionpool connectionpool.py DEBUG: https://download.waterinfo.be:443 "GET /tsmdownload/KiWIS/KiWIS?request=getRequestInfo&service=kisters&type=QueryServices&format=json&datasource=1&timezone=UTC HTTP/1.1" 200 12904
2023-04-03 08:50:04,646 requests_cache.policy.actions actions.py DEBUG: Pre-write cache checks: Passed
2023-04-03 08:50:04,667 root waterinfo.py INFO: Successful waterinfo API request with call https://download.waterinfo.be/tsmdownload/KiWIS/KiWIS?request=getRequestInfo&service=kisters&type=QueryServices&format=json&datasource=1&timezone=UTC
2023-04-03 08:50:04,672 requests_cache.backends.base base.py INFO: Resetting expiration with: 7 days, 0:00:00
2023-04-03 08:50:04,702 requests_cache.backends.base base.py DEBUG: Deleting up to 0 responses
2023-04-03 08:50:04,704 requests_cache.backends.base base.py INFO: Clearing all items from the cache
2023-04-03 08:50:04,717 requests_cache.backends.sqlite sqlite.py DEBUG: Opening connection to C:\Users\USER\AppData\Local\Temp\pywaterinfo_cache.sqlite:responses 
2023-04-03 08:50:04,762 requests_cache.backends.sqlite sqlite.py DEBUG: Opening connection to C:\Users\USER\AppData\Local\Temp\pywaterinfo_cache.sqlite:redirects 
```

**Comment by Beramos** [comment] 2023-04-20 09:05
I also ran into database locking issues when running simultaneous WaterInfo instances because SQLite does not support concurrent writing. So when two WaterInfo instances try to store a response in the cache, one of the instances will run into a filelock on the SQLite database, this locks seems to not be released properly. So the SQLite cache remains locked and the next time while trying to instantiate a new WaterInfo object, pywaterinfo is unable to connect to the cache in the constructor. Acces to the SQLite cache is probably triggered at this [line](https://github.com/fluves/pywaterinfo/blob/e55ce44e0656cb3b43bcd48808f7fde3a116532c/src/pywaterinfo/waterinfo.py#L130).

**Comment by stijnvanhoey** [comment] 2023-04-25 07:22
_(back from holiday period)_

Although I'm not able to reproduce the specific error of @frievb in a controlled setup, the usage of concurrent writing to the sqlite dbase has some limitations. I propose to do the following adjustments:
- make the cache opt-in so a user can choose to have the cache [active](https://github.com/fluves/pywaterinfo/blob/master/src/pywaterinfo/waterinfo.py#L79) or not (regular requests session). Default is no cache.
- make the requests-cache an optional dependency by providing users the option to not include requests-cache on installation. `pip install pywaterinfo[cache]` will include the cache-dependencies.
- make sure the naming of the backend [dbase is not hard-coded](https://github.com/fluves/pywaterinfo/blob/master/src/pywaterinfo/waterinfo.py#L80) and individual sessions write to separate sqlite files

@Beramos and @frievb I'll ping you in a PR I'll make asap.

**Comment by Beramos** [comment] 2023-04-26 08:19
> @frievb and @Beramos I checked this further and the stale behavior issue happens when I use requests-cache > 1.x.x, but not with older versions of requests-cache.
> 
> Could you have a check if this works also for you (as this would be a workaround in the meanwhile):
> 
> * install older version (<1.0.0) of requests-cache, e;g. `pip install requests-cache=0.9.8` in the environment where pywaterinfo was installed
> * rerun your code and check it the stale behavior is still happening?
> 
> We"ll make sure it is compatible with the new version as well, but would be good to trace back the issue.

I can confirm that downgrading request-cache to 0.9.8 resolves my problem with consecutive unit tests (a Waterinfo object is instantiate in each tests) locking the sqlite database.

**Comment by stijnvanhoey** [comment] 2023-04-26 11:59
@Beramos  and @frievb see https://github.com/fluves/pywaterinfo/pull/61 for an updated version which should support the latest version of requests-cache as well. Would be good if you could test the version of that PR (clone the repo > switch to `SVH-cache-refactor` branch, `pip install -e .[cache]` > run code to check behavior) and provide feedback on the PR.

**Comment by Beramos** [comment] 2023-04-27 07:55
@stijnvanhoey, I've tested this and non-caching works and when installing requests_cachen it seems that the locking issues have been resolved.

**Comment by frievb** [comment] 2023-04-27 10:13
@stijnvanhoey, I also tested both the workaround by downgrading requests-cache and the updated version (when caching was not activated). No more problems occurred in both cases. Thanks for the solving the issue!

**Comment by stijnvanhoey** [comment] 2023-04-27 14:10
tackled by #61, closing this issue

**Closed by stijnvanhoey** 2023-04-27 14:10 UTC
